# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bcast',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('logtype', models.CharField(max_length=32)),
                ('usagetype', models.CharField(max_length=64)),
                ('cnt_globe', models.IntegerField(blank=True, null=True)),
                ('cnt_smart', models.IntegerField(blank=True, null=True)),
                ('cnt_sun', models.IntegerField(blank=True, null=True)),
                ('cnt_unknown', models.IntegerField(blank=True, null=True)),
                ('val_origin', models.CharField(blank=True, max_length=32, null=True)),
                ('trandate', models.CharField(max_length=16)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ord_bcast_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('usagetype', models.CharField(max_length=32)),
                ('daterange_start', models.CharField(max_length=10)),
                ('daterange_end', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=150)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ord_bcast_saved_dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usagetypes',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('usagetype', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'ord_usagetypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardLastSession',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('usagetypelist', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
